services:
  db:
    image: mysql:8.0.44-debian
    container_name: perpustakaan-db
    restart: always
    cpus: 4
    mem_limit: 4G
    command: --default-authentication-plugin=mysql_native_password
    volumes:
       - ./perpustakaan-data/data:/var/lib/mysql
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_DATABASE=perpustakaan
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    ports:
      - "127.0.0.1:3307:3306"      
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "100m"
    networks:
      - perpustakaan-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  web:
    build: .
    container_name: perpustakaan-web
    restart: always
    cpus: 4
    mem_limit: 4G
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./perpustakaan-data/log:/var/log/apache2
      - .:/var/www/html
    networks:
      - perpustakaan-net
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "127.0.0.1:8081:80"       
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "100m"     
networks:
  perpustakaan-net:
    driver: bridge
